version: '3.1'

services:
  db1:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 5001:3306
    volumes:
      - db1_data:/var/lib/mysql
      - ./init-1.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 5002:3306
    volumes:
      - db2_data:/var/lib/mysql
      - ./init-2.sql:/docker-entrypoint-initdb.d/init.sql

  db3:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 5003:3306
    volumes:
      - db3_data:/var/lib/mysql
      - ./init-3.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db1_data:
  db2_data:
  db3_data:
