CREATE DATABASE IF NOT EXISTS `test`;
USE `test`;

CREATE TABLE members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DELIMITER ;;
CREATE PROCEDURE InsertDummyData()
BEGIN
    DECLARE i INT DEFAULT 2;
    WHILE i <= 100 DO
            INSERT INTO members (id, name) VALUES (i, CONCAT('Member ', i));
            SET i = i + 3;
        END WHILE;
END;;
DELIMITER ;

CALL InsertDummyData();

CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DELIMITER ;;
CREATE PROCEDURE InsertDummyDataOrders()
BEGIN
    DECLARE i INT DEFAULT 10;
    WHILE i < 20 DO
            INSERT INTO orders (id, name) VALUES (i, CONCAT('Order ', i));
            SET i = i + 1;
        END WHILE;
END;;
DELIMITER ;

CALL InsertDummyDataOrders();

